title: Perception Gaps  
author: Ans Ahmad
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is exmple for the blog hosted on the Github. 
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: ansahmad7
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
